### ISSUE TITLE
0.7.0 Nodejs module doesn't work

### ISSUE THREAD

**Issue by mahnunchik** [nextapps-de/flexsearch#159]
Nodejs module doesn't work.

`flexsearch@nextapps-de/flexsearch#0.7.0`

```
const FlexSearch = require('flexsearch');
// ReferenceError: window is not defined
//    at /node_modules/flexsearch/dist/flexsearch.node.js:34:794
```

**Comment by edsu** [comment]
I'm seeing the same thing:

```
ReferenceError: window is not defined
    at /home/ed/Projects/airwaves/node_modules/flexsearch/dist/flexsearch.node.js:34:794
    at Object.<anonymous> (/home/ed/Projects/airwaves/node_modules/flexsearch/dist/flexsearch.node.js:34:913)
    at Object.<anonymous> (/home/ed/Projects/airwaves/node_modules/flexsearch/dist/flexsearch.node.js:34:919)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by edsu** [comment]
Should we start to be concerned that this module is no longer being supported?

**Comment by talaikis** [comment]
I've used my fork for Node.js: https://www.npmjs.com/package/@talaikis/flexsearch

**Comment by kr05** [comment]
> I've used my fork for Node.js: https://www.npmjs.com/package/@talaikis/flexsearch

I tried to replicate what you did, but I can't find the src files.

**Comment by crapthings** [comment]
https://github.com/nextapps-de/flexsearch/issues/149#issuecomment-768093060

install 6.x

**Comment by ts-thomas** [comment]
Please install the latest version via NPM, which solves that issue.
